---
apiVersion: v1
kind: Config
clusters:
- name: ${cluster_name}
  cluster:
    certificate-authority: ${cluster_ca_b64}
    server: https://127.0.0.1:6443
users:
- name: ${user_name}
  user:
    client-certificate: ${user_cert_pem_b64}
    client-key: ${user_private_key_pem_b64}
contexts:
- name: default
  context:
    cluster: ${cluster_name}
    user: ${user_name}
current-context: default
preferences: {}

